### ISSUE TITLE
Include OS in tag suffix

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-codecov#7]
I recommend including the operating system in the suffix so that we don't run into naming issues when we support windows. For example `plugins/codecov:latest-window-amd64` and `plugins/codecov:latest-linux-amd64`

```
  publish_linux_amd64:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: docker
    repo: plugins/codecov
    auto_tag: true
-   auto_tag_suffix: amd64
+   auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile
    when:
      event: [ push, tag ]
```
